(define english_text '("I" "love" "Scheme"))
(define german_text '("Scheiße"))
(define lex
    '(

        ("eats" "frisst")
        ("Eve" "Abend")
        ("but" "aber")
        ("eight" "acht")
        ("monkey" "Affe")
        ("all" "alle")
        ("alone" "allein")
        ("when" "als")
        ("so" "also")
        ("old" "alt")
        ("at the" "am")
        ("at" "an")
        ("other" "andere")
        ("begin" "anfangen")
        ("anxiety" "Angst")
        ("reply" "antworten")
        ("answer" "beantworten")
        ("Apple" "Apfel")
        ("job" "Arbeit")
        ("work" "arbeiten")
        ("doctor" "Arzt")
        ("also" "auch")
        ("on" "auf")
        ("eye" "Auge")
        ("out" "aus")
        ("car" "Auto")
        ("bathe" "baden")
        ("soon" "bald")
        ("ball" "Ball")
        ("build" "bauen")
        ("Farmer" "Bauer")
        ("tree" "Baum")
        ("at" "bei")
        ("both" "beide")
        ("at the" "beim")
        ("leg" "Bein")
        ("example" "Beispiel")
        ("goes" "geht")
        ("bite" "beißen")
        ("get" "bekommen")
        ("mountain" "Berg")
        ("better" "besser")
        ("bed" "Bett")
        ("picture" "Bild")
        ("am" "bin")
        ("to" "bis")
        ("blue" "blau")
        ("stay" "bleiben")
        ("flower" "Blume")
        ("ground" "Boden")
        ("evil" "böse")
        ("need" "brauchen")
        ("brown" "braun")
        ("letter" "Brief")
        ("bring" "bringen")
        ("loaf" "Brot")
        ("Brothers" "Bruder")
        ("book" "Buch")
        ("there" "da")
        ("with it" "dabei")
        ("for this" "dafür")
        ("in order to" "damit")
        ("after that" "danach")
        ("then" "dann")
        ("on it" "daran")
        ("thereon" "darauf")
        ("in this" "darin")
        ("the" "das")
        ("last" "dauern")
        ("from that" "davon")
        ("to" "dazu")
        ("your" "dein")
        ("the" "dem")
        ("the" "den")
        ("think" "denken")
        ("because" "denn")
        ("the" "der")
        ("that's why" "deshalb")
        ("you" "dich")
        ("thick" "dick")
        ("the" "die")
        ("thing" "Ding")
        ("you" "dir")
        ("but" "doch")
        ("Village" "Dorf")
        ("there" "dort")
        ("outside" "draußen")
        ("rotate" "drehen")
        ("three" "drei")
        ("stupid" "dumm")
        ("dark" "dunkel")
        ("by" "durch")
        ("allowed to" "dürfen")
        ("actually" "eigentlich")
        ("a" "ein")
        ("a" "eine")
        ("one" "einer")
        ("easy" "einfach")
        ("some" "einige")
        ("some" "einigen")
        ("Computer Science" "Informatik")
        ("once" "einmal")
        ("ice" "Eis")
        ("parents" "Eltern")
        ("The End" "Ende")
        ("Finally" "endlich")
        ("earth" "Erde")
        ("explain" "erklären")
        ("frighten" "erschrecken")
        ("awesome" "toll")
        ("first" "erst")
        ("tell" "erzählen")
        ("eat" "essen")
        ("something" "etwas")
        ("drive" "fahren")
        ("bicycle" "Fahrrad")
        ("moves" "fährt")
        ("fall" "fallen")
        ("family" "Familie")
        ("catch" "fangen")
        ("nearly" "fast")
        ("absence" "fehlen")
        ("window" "Fenster")
        ("vacation" "Ferien")
        ("finished" "fertig")
        ("firmly" "fest")
        ("Fire" "Feuer")
        ("fell" "fiel")
        ("Find" "finden")
        ("finger" "Finger")
        ("fish" "Fisch")
        ("bottle" "Flasche")
        ("fly" "fliegen")
        ("question" "Frage")
        ("ask" "fragen")
        ("woman" "Frau")
        ("free" "frei")
        ("eat" "fressen")
        ("joy" "Freude")
        ("looking forward" "freuen")
        ("friend" "Freund")
        ("Happy" "fröhlich")
        ("early" "früh")
        ("earlier" "früher")
        ("lead" "führen")
        ("five" "fünf")
        ("For" "für")
        ("foot" "Fuß")
        ("Soccer" "Fußball")
        ("gave" "gab")
        ("all" "ganz")
        ("at all" "gar")
        ("garden" "Garten")
        ("give" "geben")
        ("birthday" "Geburtstag")
        ("dangerous" "gefährlich")
        ("versus" "gegen")
        ("walk" "gehen")
        ("belong" "gehören")
        ("yellow" "gelb")
        ("Scheme" "Scheiße")
        ("money" "Geld")
        ("I agree" "genau")
        ("straight" "gerade")
        ("gladly" "gern")
        ("gift" "Geschenk")
        ("story" "Geschichte")
        ("face" "Gesicht")
        ("yesterday" "gestern")
        ("healthy" "gesund")
        ("win" "gewinnen")
        ("gives" "gibt")
        ("went" "ging")
        ("Glass" "Glas")
        ("believe" "glauben")
        ("equal" "gleich")
        ("happiness" "Glück")
        ("happy" "glücklich")
        ("God" "Gott")
        ("big" "groß")
        ("green" "grün")
        ("Well" "gut")
        ("hair" "Haar")
        ("have" "haben")
        ("half" "halb")
        ("hold" "halten")
        ("hand" "Hand")
        ("hang" "hängen")
        ("hard" "hart")
        ("Rabbit" "Hase")
        ("Has" "hat")
        ("would have" "hatte")
        ("had" "hatten")
        ("House" "Haus")
        ("hot" "heiß")
        ("be called" "heißen")
        ("help" "helfen")
        ("here" "her")
        ("out" "heraus")
        ("Mr" "Herr")
        ("heart" "Herz")
        ("today" "heute")
        ("here" "hier")
        ("Help" "Hilfe")
        ("sky" "Himmel")
        ("down" "hin")
        ("into it" "hinein")
        ("Behind" "hinter")
        ("high" "hoch")
        ("fetch" "holen")
        ("Listen" "hören")
        ("dog" "Hund")
        ("hunger" "Hunger")
        ("I" "ich")
        ("him" "ihm")
        ("him" "ihn")
        ("her" "ihr")
        ("in the" "im")
        ("always" "immer")
        ("in" "in")
        ("ins" "ins")
        ("is" "ist")
        ("Yes" "ja")
        ("year" "Jahr")
        ("everyone" "jeder")
        ("love" "liebe")
        ("now" "jetzt")
        ("young" "jung")
        ("Boy" "Junge")
        ("cold" "kalt")
        ("came" "kam")
        ("can" "kann")
        ("cat" "Katze")
        ("buy" "kaufen")
        ("no" "kein")
        ("know" "kennen")
        ("child" "Kind")
        ("great" "Klasse")
        ("small" "klein")
        ("climb" "klettern")
        ("Cook" "kochen")
        ("come" "kommen")
        ("can" "können")
        ("head" "Kopf")
        ("ill" "krank")
        ("kitchen" "Küche")
        ("short" "kurz")
        ("laugh" "lachen")
        ("country" "Land")
        ("long" "lang")
        ("slowly" "langsam")
        ("read" "las")
        ("let" "lassen")
        ("run" "laufen")
        ("according to" "laut")
        ("Life" "leben")
        ("lay" "legen")
        ("Teacher" "Lehrer")
        ("Teacher" "Lehrerin")
        ("light" "leicht")
        ("quiet" "leise")
        ("learn" "lernen")
        ("read" "lesen")
        ("latest" "letzte")
        ("People" "Leute")
        ("light" "Licht")
        ("dear" "lieb")
        ("lie" "liegen")
        ("let" "ließ")
        ("hole" "Loch")
        ("Come on" "los")
        ("air" "Luft")
        ("funny" "lustig")
        ("do" "machen")
        ("girl" "Mädchen")
        ("times" "mal")
        ("man" "man")
        ("man" "Mann")
        ("mouse" "Maus")
        ("sea" "Meer")
        ("more" "mehr")
        ("my" "mein")
        ("man" "Mensch")
        ("notice" "merken")
        ("me" "mich")
        ("milk" "Milch")
        ("minute" "Minute")
        ("me" "mir")
        ("With" "mit")
        ("like" "mögen")
        ("possible" "möglich")
        ("month" "Monat")
        ("tired" "müde")
        ("music" "Musik")
        ("have to" "müssen")
        ("mother" "Mutter")
        ("Mom" "Mutti")
        ("after" "nach")
        ("next" "nächste")
        ("night" "Nacht")
        ("close" "nah")
        ("Surname" "Name")
        ("namely" "nämlich")
        ("nose" "Nase")
        ("wet" "nass")
        ("Naturally" "natürlich")
        ("Next" "neben")
        ("to take" "nehmen")
        ("No" "nein")
        ("call" "nennen")
        ("New" "neu")
        ("nine" "neun")
        ("Not" "nicht")
        ("Nothing" "nichts")
        ("never" "nie")
        ("takes" "nimmt")
        ("still" "noch")
        ("now" "nun")
        ("just" "nur")
        ("if" "ob")
        ("above" "oben")
        ("or" "oder")
        ("open" "offen")
        ("open" "öffnen")
        ("often" "oft")
        ("without" "ohne")
        ("granny" "Oma")
        ("uncle" "Onkel")
        ("Grandpa" "Opa")
        ("pack" "packen")
        ("horse" "Pferd")
        ("place" "Platz")
        ("suddenly" "plötzlich")
        ("police" "Polizei")
        ("wheel" "Rad")
        ("calculate" "rechnen")
        ("rich" "reich")
        ("horse riding" "reiten")
        ("run" "rennen")
        ("correct" "richtig")
        ("red" "rot")
        ("call" "rufen")
        ("calm" "ruhig")
        ("round" "rund")
        ("Thing" "Sache")
        ("say" "sagen")
        ("create" "schaffen")
        ("watch" "schauen")
        ("seem to be" "scheinen")
        ("give" "schenken")
        ("send" "schicken")
        ("ship" "Schiff")
        ("sleep" "schlafen")
        ("beat" "schlagen")
        ("bad" "schlecht")
        ("bad" "schlimm")
        ("Enough" "Schluss")
        ("snow" "Schnee")
        ("fast" "schnell")
        ("beautiful" "schon")
        ("beautiful" "schön")
        ("write" "schreiben")
        ("scream" "schreien")
        ("shoe" "Schuh")
        ("school" "Schule")
        ("student" "Schüler")
        ("black" "schwarz")
        ("heavy" "schwer")
        ("sister" "Schwester")
        ("swim" "schwimmen")
        ("six" "sechs")
        ("lake" "See")
        ("see" "sehen")
        ("very" "sehr")
        ("be" "sein")
        ("since" "seit")
        ("page" "Seite")
        ("even" "selbst")
        ("put" "setzen")
        ("themselves" "sich")
        ("for sure" "sicher")
        ("she" "sie")
        ("seven" "sieben")
        ("sees" "sieht")
        ("are" "sind")
        ("sing" "singen")
        ("sit" "sitzen")
        ("so" "so")
        ("right away" "sofort")
        ("son" "Sohn")
        ("should" "sollen")
        ("summer" "Sommer")
        ("Sun" "Sonne")
        ("Sunday" "Sonntag")
        ("otherwise" "sonst")
        ("fun" "Spaß")
        ("late" "spät")
        ("later" "später")
        ("game" "Spiel")
        ("play" "spielen")
        ("speak" "sprechen")
        ("leap" "springen")
        ("city" "Stadt")
        ("strong" "stark")
        ("stand" "stehen")
        ("climb" "steigen")
        ("stone" "Stein")
        ("Job" "Stelle")
        ("put" "stellen")
        ("Street" "Straße")
        ("piece" "Stück")
        ("hour" "Stunde")
        ("search" "suchen")
        ("Day" "Tag")
        ("aunt" "Tante")
        ("Plate" "Teller")
        ("deep" "tief")
        ("animal" "Tier")
        ("table" "Tisch")
        ("dead" "tot")
        ("wear" "tragen")
        ("Sad" "traurig")
        ("meet" "treffen")
        ("drink" "trinken")
        ("to do" "tun")
        ("door" "Tür")
        ("do gymnastics" "turnen")
        ("about" "über")
        ("all over" "überall")
        ("Clock" "Uhr")
        ("around" "um")
        ("and" "und")
        ("us" "uns")
        ("our" "unser")
        ("below" "unten")
        ("under" "unter")
        ("father" "Vater")
        ("dad" "Vati")
        ("forget" "vergessen")
        ("sell" "verkaufen")
        ("lose" "verlieren")
        ("hide" "verstecken")
        ("understand" "verstehen")
        ("attempt" "versuchen")
        ("a lot of" "viel")
        ("maybe" "vielleicht")
        ("four" "vier")
        ("bird" "Vogel")
        ("full" "voll")
        ("from" "vom")
        ("of" "von")
        ("in front" "vor")
        ("past" "vorbei")
        ("dare" "Wagen")
        ("true" "wahr")
        ("Forest" "Wald")
        ("was" "war")
        ("were" "waren")
        ("warm" "warm")
        ("waiting" "warten")
        ("Why" "warum")
        ("What" "was")
        ("wash" "waschen")
        ("water" "Wasser")
        ("path" "weg")
        ("path" "Weg")
        ("Christmas" "Weihnachten")
        ("because" "weil")
        ("cry" "weinen")
        ("White" "weiß")
        ("far" "weit")
        ("continue" "weiter")
        ("world" "Welt")
        ("little" "wenig")
        ("if" "wenn")
        ("who" "wer")
        ("will" "werden")
        ("throw" "werfen")
        ("Weather" "Wetter")
        ("important" "wichtig")
        ("as" "wie")
        ("again" "wieder")
        ("Meadow" "Wiese")
        ("want" "will")
        ("winter" "Winter")
        ("we" "wir")
        ("becomes" "wird")
        ("for real" "wirklich")
        ("knowledge" "wissen")
        ("Knowledge" "Wissen")
        ("Where" "wo")
        ("week" "Woche")
        ("well" "wohl")
        ("dwell" "wohnen")
        ("flat" "Wohnung")
        ("want" "wollen")
        ("word" "Wort")
        ("wish" "wünschen")
        ("number" "Zahl")
        ("ten" "zehn")
        ("demonstrate" "zeigen")
        ("time" "Zeit")
        ("newspaper" "Zeitung")
        ("pull" "ziehen")
        ("room" "Zimmer")
        ("to" "zu")
        ("train" "Zug")
        ("to the" "zum")
        ("to" "zur")
        ("back" "zurück")
        ("together" "zusammen")
        ("two" "zwei")
        ("between" "zwischen")
    )
)

(define print_word
  (lambda (word)
    (display (string-append word " ") )))

(define translate
  (lambda (from_index to_index text)
    (map 
      (lambda (word) 
        (map 
          (lambda (lex_entry)
            (if (eqv? (string-downcase word) (string-downcase (list-ref lex_entry from_index)))
              (print_word (list-ref lex_entry to_index)))
          )
        lex)
      )
    text)
  )
)

(print "--------------------------------------------------")
(print "English -> German:")
(translate 0 1 english_text)

(print "")
(print "--------------------------------------------------")
(print "German -> English:")
(translate 1 0 german_text)
(print "")
(print "--------------------------------------------------")
